version: '3.9'

networks:
  dokploy-network:
    external: true

services:
  web:
    image: chatwoot/chatwoot:latest
    restart: always
    env_file: .env
    environment:
      - RAILS_ENV=production
      - NODE_ENV=production
      - FRONTEND_URL=${FRONTEND_URL}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
      - redis
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.${PROJECT_NAME}.rule=Host(`${FRONTEND_URL}`)
      - traefik.http.routers.${PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.${PROJECT_NAME}.tls.certresolver=letsencrypt
      - traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=3000

  sidekiq:
    image: chatwoot/chatwoot:latest
    command: bundle exec sidekiq -C config/sidekiq.yml
    restart: always
    env_file: .env
    environment:
      - RAILS_ENV=production
      - NODE_ENV=production
    depends_on:
      - postgres
      - redis
    networks:
      - dokploy-network

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: chatwoot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - dokploy-network

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - redis:/data
    networks:
      - dokploy-network

volumes:
  postgres:
  redis:
